name: Update PDF
# Derived from this handy tutorial: https://github.com/pandoc/pandoc-action-example

# Runs whenever either the CV.md or the template changes.
on:
  push:
    paths:
      - CV.md
      - cv.template.tex
      - .github/workflows/main.yml
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  create_pdf:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Run APT
        # Pandoc = self-explanatory
        # fonts-liberation = The main font I use
        # poppler-utils = Required for the automated PDF->PNG conversion later in this workflow.
        run: |
          sudo apt update
          sudo apt install pandoc fonts-liberation poppler-utils
      - name: Install LaTeX
        # see https://tug.org/texlive/quickinstall.html
        # For `install-tl`, see https://tug.org/texlive/doc/install-tl.html
        # NOTE: Overwriting texlive directory so that it remains stable.
        run: |
          wget https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
          zcat < install-tl-unx.tar.gz | tar xf - # note final - on that command line
          cd install-tl-2*
          sudo perl ./install-tl --no-interaction --scheme=small --no-doc-install --no-src-install -texdir /usr/local/texlive/current
          export PATH=/usr/local/texlive/current/bin/x86_64-linux:$PATH
      - name: Install LaTeX Packages
        # NOTE: sudo has a different PATH -> use absolute path to binary!
        # fontawesome6 = Provides Icons for contact section
        run: |
          sudo /usr/local/texlive/current/bin/x86_64-linux/tlmgr init-usertree
          sudo /usr/local/texlive/current/bin/x86_64-linux/tlmgr update --self --all
          sudo /usr/local/texlive/current/bin/x86_64-linux/tlmgr install fontawesome6
          sudo /usr/local/texlive/current/bin/x86_64-linux/tlmgr install sectsty
      - name: Produce PDF
        run: |
          export PATH=/usr/local/texlive/current/bin/x86_64-linux:$PATH
          pandoc --output=CV.pdf --pdf-engine=xelatex --template=cv.template.tex CV.md
          pandoc --output=CV.stub.html --embed-resources --template=cv.template.htm CV.md
      - name: Update Preview PNG
        # See https://askubuntu.com/a/50180
        run: |
          pdftoppm CV.pdf CV -png -f 1 -singlefile
      # Apparently we have to explicitly set the git parameters here
      - name: Set Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit PDF
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: Recreate PDF"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
