name: Update PDF
# Derived from this handy tutorial: https://github.com/pandoc/pandoc-action-example

# Runs whenever either the CV.md or the template changes.
on:
  push:
    paths:
      - CV.md
      - cv.template.tex
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  create_pdf:
    name: Create PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Install Dependencies
        # Pandoc = self-explanatory
        # fonts-liberation = The main font I use
        # texlive-base = The LaTeX base package
        # texlive-xetex = The XeLaTeX compiler
        # texlive-latex-extra = A small set of additional TeX packages
        # texlive-lang-english = Language data for English
        # texlive-lang-greek = Another package that turned out to be required as of Jan 14, 2025
        # poppler-utils = Required for the automated PDF->PNG conversion later in this workflow.
        run: |
          sudo apt update
          sudo apt install pandoc fonts-liberation texlive-base texlive-xetex texlive-latex-extra texlive-lang-english texlive-lang-greek poppler-utils
      - name: Produce PDF
        run: |
          pandoc --output=CV.pdf --pdf-engine=xelatex --template=cv.template.tex CV.md
          pandoc --output=CV.stub.html --embed-resources --template=cv.template.htm CV.md
      - name: Update Preview PNG
        # See https://askubuntu.com/a/50180
        run: |
          pdftoppm CV.pdf CV -png -f 1 -singlefile
      # Apparently we have to explicitly set the git parameters here
      - name: Set Git config
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Commit PDF
        run: |
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore: Recreate PDF"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
